name: CI

on:
    push:
        branches:
            - main
            - '[0-9]+.[0-9]+'
    pull_request: ~

jobs:
    cs-fix:
        name: Run code style check
        runs-on: "ubuntu-22.04"
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP Action
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.1'
                  coverage: none
                  extensions: 'pdo_sqlite, gd'
                  tools: cs2pr

            - uses: ramsey/composer-install@v2
              with:
                  dependency-versions: highest

            - name: Run code style check
              run: composer run-script check-cs -- --format=checkstyle | cs2pr

    tests:
        name: Unit tests
        runs-on: "ubuntu-22.04"
        timeout-minutes: 15

        strategy:
            fail-fast: false
            matrix:
                php:
                    - '7.3'
                    - '7.4'
                    - '8.0'
                    - '8.2'

        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP Action
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
                  extensions: pdo_sqlite, gd
                  tools: cs2pr

            - uses: ramsey/composer-install@v2
              with:
                  dependency-versions: highest

            - name: Run PHPStan analysis
              run: composer run-script phpstan

            - name: Setup problem matchers for PHPUnit
              run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Run unit test suite
              run: composer test

    integration-tests:
        name: "REST integration tests"
        uses: ./.github/workflows/integration-tests-callable.yaml
